name: Deploy

on:
  push:
    branches: 
    - 'master'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Login to Docker registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 
        
    
        - name: Build And Push
          uses: docker/build-push-action@v5
          with:
            push: true
            context: .
            file: ./Dockerfile
            build-args: |
              SUPABASE_URL=${{ secrets.SUPABASE_URL }}
              SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
              DATABASE_HOST=${{ secrets.DATABASE_HOST }}
              DATABASE_USER=${{ secrets.DATABASE_USER }}
              DATABASE_NAME=${{ secrets.DATABASE_NAME }}
              DATABASE_PORT=${{ secrets.DATABASE_PORT }}
              DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
              PRODUCTION=${{ secrets.PRODUCTION }}
            tags: erlanggaak/${{ secrets.IMAGE_NAME }}:latest

    deploy:
        runs-on: ubuntu-latest
        needs: publish  # Wait for publish job to complete
        steps:
          - uses: actions/checkout@v4
            
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.GCP_STATIC_IP }}
              username: ${{ secrets.GCP_USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              script: |
                docker container rm -f forum || true
                docker image rm -f ${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest || true
                docker run --name forum -d -p 8020:8000 ${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest